// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtKI6UF9eTD6DtprelejzCzvklibtJolA',
    appId: '1:228691592709:web:39f10f7da06f2e92cd7e6c',
    messagingSenderId: '228691592709',
    projectId: 'fishingline-97515',
    authDomain: 'fishingline-97515.firebaseapp.com',
    storageBucket: 'fishingline-97515.appspot.com',
    measurementId: 'G-JMCB63Z62T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm5Go03I0PVyrKqmnIhSyL9NhHqxex-0g',
    appId: '1:228691592709:android:629bfbd619176b5acd7e6c',
    messagingSenderId: '228691592709',
    projectId: 'fishingline-97515',
    storageBucket: 'fishingline-97515.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmEzWOGfQjgFdV3Z9BiYQcmwPsyMarB2k',
    appId: '1:228691592709:ios:fa05d91a8773a757cd7e6c',
    messagingSenderId: '228691592709',
    projectId: 'fishingline-97515',
    storageBucket: 'fishingline-97515.appspot.com',
    androidClientId: '228691592709-pnt7ullf16t8nnm54qin57ju93k2egu6.apps.googleusercontent.com',
    iosClientId: '228691592709-r1d16v4g73o8im1s8dbdfijctci494fg.apps.googleusercontent.com',
    iosBundleId: 'com.example.fishingline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmEzWOGfQjgFdV3Z9BiYQcmwPsyMarB2k',
    appId: '1:228691592709:ios:b9de58ff86eac96ccd7e6c',
    messagingSenderId: '228691592709',
    projectId: 'fishingline-97515',
    storageBucket: 'fishingline-97515.appspot.com',
    androidClientId: '228691592709-pnt7ullf16t8nnm54qin57ju93k2egu6.apps.googleusercontent.com',
    iosClientId: '228691592709-7jfrop2qipclnela04r0u92anktfnp20.apps.googleusercontent.com',
    iosBundleId: 'com.example.fishingline.RunnerTests',
  );
}
