// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5joN2w8Rj2l5h3dB77FUYBfyiDBCjP28',
    appId: '1:174925084469:web:9a712bc3d75ee55454fe7c',
    messagingSenderId: '174925084469',
    projectId: 'fishingline-91805',
    authDomain: 'fishingline-91805.firebaseapp.com',
    storageBucket: 'fishingline-91805.appspot.com',
    measurementId: 'G-FM873S14BG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW5cF04NbnG3CQFS0LF97xlbKqFNuEUV0',
    appId: '1:174925084469:android:d3c0beaae19ce38454fe7c',
    messagingSenderId: '174925084469',
    projectId: 'fishingline-91805',
    storageBucket: 'fishingline-91805.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfB7ZkbDKv0DJ8infEl4XA4oTFFI0_EX8',
    appId: '1:174925084469:ios:f6657037623ee06a54fe7c',
    messagingSenderId: '174925084469',
    projectId: 'fishingline-91805',
    storageBucket: 'fishingline-91805.appspot.com',
    iosBundleId: 'com.example.fishingline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfB7ZkbDKv0DJ8infEl4XA4oTFFI0_EX8',
    appId: '1:174925084469:ios:caf16db86ff30bac54fe7c',
    messagingSenderId: '174925084469',
    projectId: 'fishingline-91805',
    storageBucket: 'fishingline-91805.appspot.com',
    iosBundleId: 'com.example.fishingline.RunnerTests',
  );
}
